name: Dispatch test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

jobs:
  clean_everything:
    runs-on: ubuntu-latest
    steps:
      - name: Cleaning the DB
        run: echo "Clean the db"

      - name: Print the selected Environment
        run: echo "The Environment is ${{ github.event.inputs.environment }}"
