name: Dispatch test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

jobs:
  clean_everything:
    runs-on: ubuntu-latest
    steps:
      - name: Cleaning the DB
        run: echo "Clean the db"

      - name: If the environment is staging
        if: ${{github.event.inputs.environment ==  staging}}
        run: echo "The Environment is staging"

      - name: If the environment is production
        if: ${{github.event.inputs.environment ==  production}}
        run: echo "The Environment is production"
